# Generated by Django 2.2.7 on 2019-12-11 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 11, 11, 9, 37, 575858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 11, 9, 37, 575489)),
        ),
    ]
