# Generated by Django 2.2.7 on 2020-02-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='internship_thumbnail',
            field=models.ImageField(upload_to='media/thumbnails/'),
        ),
    ]
