# Generated by Django 2.2.8 on 2019-12-11 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adduser',
            old_name='date',
            new_name='date_joined',
        ),
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 9, 37, 12, 732491)),
        ),
    ]
