# Generated by Django 2.2.7 on 2020-03-05 13:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data_status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('WAITING', 'WAITING'), ('UNDER REVIEW', 'UNDER REVIEW')], default='WAITING', max_length=20)),
                ('subtopic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fossee_math_pages.Subtopic')),
            ],
        ),
    ]
