# Generated by Django 2.2.7 on 2019-12-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='data',
            name='subtopic',
            field=models.CharField(max_length=255),
        ),
    ]
