# Generated by Django 2.2.7 on 2020-01-23 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='internship_quote',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_quote_author',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
