# Generated by Django 2.2.8 on 2019-12-03 15:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0002_addintern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addintern',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='addintern',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
