# Generated by Django 2.2.7 on 2020-03-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0002_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
