# Generated by Django 2.2.8 on 2019-12-11 16:36

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0002_auto_20191211_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='joined_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 16, 36, 39, 640723)),
        ),
    ]
