# Generated by Django 2.2.7 on 2019-12-12 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0002_auto_20191212_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 23, 22, 32, 916623)),
        ),
    ]
