# Generated by Django 2.2.7 on 2019-12-12 15:25

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0002_auto_20191212_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 20, 55, 14, 740235)),
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
