# Generated by Django 2.2.7 on 2019-12-07 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0002_auto_20191207_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('SUSPENDED', 'SUSPENDED')], default='INACTIVE', max_length=255),
        ),
        migrations.AddField(
            model_name='data',
            name='aproval_ststus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 11, 49, 32, 87752)),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
