# Generated by Django 2.2.8 on 2019-12-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0003_auto_20191229_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_temp_password',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
