# Generated by Django 2.2.8 on 2019-12-13 11:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0003_auto_20191213_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 17, 25, 52, 398066)),
        ),
        migrations.AlterField(
            model_name='data',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
