# Generated by Django 2.2.7 on 2019-12-13 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0003_auto_20191213_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 16, 22, 5, 378311)),
        ),
    ]
