# Generated by Django 2.2.8 on 2019-12-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0003_auto_20191203_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='addintern',
            name='role',
            field=models.CharField(choices=[('INTERN', 'Intern'), ('STAFF', 'Staff')], default='INTERN', max_length=20),
        ),
    ]
