# Generated by Django 2.2.8 on 2019-12-03 16:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0004_addintern_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addintern',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None, unique=True),
        ),
    ]
