# Generated by Django 2.2.8 on 2019-12-07 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0004_auto_20191207_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 14, 48, 6, 49809)),
        ),
    ]
