# Generated by Django 2.2.8 on 2019-12-11 10:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0004_auto_20191211_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 15, 45, 23, 964093)),
        ),
    ]
