# Generated by Django 2.2.8 on 2019-12-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0005_auto_20191230_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_role',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('STAFF', 'STAFF')], default='INTERN', max_length=20),
        ),
    ]
