# Generated by Django 2.2.8 on 2019-12-11 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0005_auto_20191211_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 15, 57, 53, 572282)),
        ),
    ]
