# Generated by Django 2.2.8 on 2019-12-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0005_auto_20191203_2215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddIntern',
            new_name='AddUser',
        ),
    ]
