# Generated by Django 2.2.8 on 2019-12-10 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0005_auto_20191207_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='data',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 16, 58, 54, 304322)),
        ),
    ]
