# Generated by Django 2.2.8 on 2019-12-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0006_auto_20191230_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='internship_thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
