# Generated by Django 2.2.8 on 2019-12-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0006_auto_20191203_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('adduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fossee_math_pages.AddUser')),
            ],
            bases=('fossee_math_pages.adduser',),
        ),
    ]
