# Generated by Django 2.2.7 on 2020-02-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0006_auto_20200206_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='internship_thumbnail',
            field=models.FileField(upload_to=''),
        ),
    ]
