# Generated by Django 2.2.8 on 2019-12-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0007_userform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='AddUserView',
        ),
    ]
