# Generated by Django 2.2.8 on 2020-01-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0007_auto_20191230_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='INACTIVE', max_length=255),
        ),
    ]
