# Generated by Django 2.2.7 on 2020-01-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0008_auto_20200102_1633'),
        ('fossee_math_pages', '0008_auto_20200102_1622'),
    ]

    operations = [
    ]
