# Generated by Django 2.2.7 on 2020-02-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee_math_pages', '0008_auto_20200206_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
